version: '3.9'
services:
  db:
    build: 
      context: .
      dockerfile: apps/postgres/Dockerfile
    image: online-market-db-image
    container_name: online-market-db-container
    restart: always
    ports:
      - 5433:5432
    volumes: 
      - online-market-db-volume:/var/lib/postgresql/data
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: online-market-web-image
    container_name: online-market-web-container
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    depends_on:
      - db
    networks:
      - default
    volumes:
      - server_root_files:/app/wwwroot

volumes:
  server_root_files:
    driver: local
  online-market-db-volume:
    driver: local